# Form implementation generated from reading ui file 'edit_freeway.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1400, 800)
        Widget.setMinimumSize(QtCore.QSize(1400, 800))
        Widget.setMaximumSize(QtCore.QSize(1400, 800))
        self.general_settings_btn = QtWidgets.QPushButton(Widget)
        self.general_settings_btn.setGeometry(QtCore.QRect(10, 10, 141, 32))
        self.general_settings_btn.setObjectName("general_settings_btn")
        self.freeway_img = QtWidgets.QLabel(Widget)
        self.freeway_img.setGeometry(QtCore.QRect(1060, 10, 291, 781))
        self.freeway_img.setText("")
        self.freeway_img.setPixmap(QtGui.QPixmap("road.gif"))
        self.freeway_img.setObjectName("freeway_img")
        self.verticalLayoutWidget = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 160, 501, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.section_id = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.section_id.setFont(font)
        self.section_id.setObjectName("section_id")
        self.verticalLayout.addWidget(self.section_id)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.add_vehicles_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add_vehicles_btn.setObjectName("add_vehicles_btn")
        self.verticalLayout.addWidget(self.add_vehicles_btn)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 750, 290, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_settings_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.import_settings_btn.setObjectName("import_settings_btn")
        self.horizontalLayout.addWidget(self.import_settings_btn)
        self.settings_spin = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.settings_spin.setObjectName("settings_spin")
        self.settings_spin.addItem("")
        self.horizontalLayout.addWidget(self.settings_spin)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.general_settings_btn.setText(_translate("Widget", "General Settings"))
        self.title.setText(_translate("Widget", "Edit Freeway Section"))
        self.section_id.setText(_translate("Widget", "Section ID"))
        self.add_vehicles_btn.setText(_translate("Widget", "Add Vehicles"))
        self.import_settings_btn.setText(_translate("Widget", "Import Settings"))
        self.settings_spin.setItemText(0, _translate("Widget", "Custom (Default)"))
