# Form implementation generated from reading ui file 'new_frontend/pyqt_ui/trafficLightSettingPopUp.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrafficLightSettingPopUp(object):
    def setupUi(self, TrafficLightSettingPopUp):
        TrafficLightSettingPopUp.setObjectName("TrafficLightSettingPopUp")
        TrafficLightSettingPopUp.resize(1400, 800)
        TrafficLightSettingPopUp.setMinimumSize(QtCore.QSize(1400, 800))
        TrafficLightSettingPopUp.setMaximumSize(QtCore.QSize(1400, 800))
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=TrafficLightSettingPopUp)
        self.buttonBox.setGeometry(QtCore.QRect(480, 460, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=TrafficLightSettingPopUp)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(490, 390, 331, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.ThirdContainer = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.ThirdContainer.setContentsMargins(0, 0, 0, 0)
        self.ThirdContainer.setObjectName("ThirdContainer")
        self.thirdLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        self.thirdLabel.setObjectName("thirdLabel")
        self.ThirdContainer.addWidget(self.thirdLabel)
        self.thirdComboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_3)
        self.thirdComboBox.setObjectName("thirdComboBox")
        self.ThirdContainer.addWidget(self.thirdComboBox)
        self.thirdSpinBox = QtWidgets.QSpinBox(parent=self.horizontalLayoutWidget_3)
        self.thirdSpinBox.setMaximum(255)
        self.thirdSpinBox.setObjectName("thirdSpinBox")
        self.ThirdContainer.addWidget(self.thirdSpinBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=TrafficLightSettingPopUp)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(490, 250, 331, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.FirstContainer = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.FirstContainer.setContentsMargins(0, 0, 0, 0)
        self.FirstContainer.setObjectName("FirstContainer")
        self.firstLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.firstLabel.setObjectName("firstLabel")
        self.FirstContainer.addWidget(self.firstLabel)
        self.firstComboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.firstComboBox.setObjectName("firstComboBox")
        self.FirstContainer.addWidget(self.firstComboBox)
        self.firstSpinBox = QtWidgets.QSpinBox(parent=self.horizontalLayoutWidget)
        self.firstSpinBox.setMaximum(255)
        self.firstSpinBox.setObjectName("firstSpinBox")
        self.FirstContainer.addWidget(self.firstSpinBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=TrafficLightSettingPopUp)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(490, 320, 331, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.SecondContainer = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.SecondContainer.setContentsMargins(0, 0, 0, 0)
        self.SecondContainer.setObjectName("SecondContainer")
        self.secondLabel = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.secondLabel.setObjectName("secondLabel")
        self.SecondContainer.addWidget(self.secondLabel)
        self.secondComboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_2)
        self.secondComboBox.setObjectName("secondComboBox")
        self.SecondContainer.addWidget(self.secondComboBox)
        self.secondSpinBox = QtWidgets.QSpinBox(parent=self.horizontalLayoutWidget_2)
        self.secondSpinBox.setMaximum(255)
        self.secondSpinBox.setObjectName("secondSpinBox")
        self.SecondContainer.addWidget(self.secondSpinBox)

        self.retranslateUi(TrafficLightSettingPopUp)
        QtCore.QMetaObject.connectSlotsByName(TrafficLightSettingPopUp)

    def retranslateUi(self, TrafficLightSettingPopUp):
        _translate = QtCore.QCoreApplication.translate
        TrafficLightSettingPopUp.setWindowTitle(_translate("TrafficLightSettingPopUp", "Widget"))
        self.thirdLabel.setText(_translate("TrafficLightSettingPopUp", "Third"))
        self.firstLabel.setText(_translate("TrafficLightSettingPopUp", "First"))
        self.secondLabel.setText(_translate("TrafficLightSettingPopUp", "Second"))
